name: mirror
description: "A premium Flutter mirror application."

# mistake public upload issue
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Camera Main package
  camera: ^0.11.0+2
  gal: ^2.3.2
  path_provider: ^2.1.2

  # Screen Brightness
  screen_brightness: ^2.1.7

  # Icon and sharing
  cupertino_icons: ^1.0.8
  share_plus: ^13.0.0
  shared_preferences: ^2.5.5

  # Native Screen package
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Icon Package
  flutter_launcher_icons: ^0.13.1

# Launcher Icon
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"

  # Icon Background
  adaptive_icon_background: "#121212"

  # main icon generate
  adaptive_icon_foreground: "assets/images/app_icon.png"

# Native splash screen configuration
flutter_native_splash:

color: "#121212"

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.png