name: mirror
description: "A premium Flutter mirror application."

# এটি ব্যবহার করলে ভুল করে পাবলিকে আপলোড হবে না
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # ক্যামেরার মেইন প্যাকেজ
  camera: ^0.11.0+2
  gal: ^2.3.2
  path_provider: ^2.1.2

  # স্ক্রিন ব্রাইটনেস কন্ট্রোল (বর্ডার লাইট ফিচারের জন্য)
  # আমি এটি ২.১.৭ করে দিয়েছি যাতে এরর না আসে
  screen_brightness: ^2.1.7

  # আইকনের জন্য
  cupertino_icons: ^1.0.8
  share_plus: ^13.0.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  # কোড ক্লিন রাখার জন্য লিন্টস
  flutter_lints: ^3.0.0

flutter:
  # মেটেরিয়াল ডিজাইন আইকন এবং উইজেট ব্যবহারের জন্য
  uses-material-design: true